### ISSUE TITLE
Binding library for mac now fails 

### ISSUE THREAD

**Issue by jensstigaard** [cryptlex/lexactivator-js#9]
Hi Adnan

The most recent version enables ElectronJS cross-building (building to Windows from a Mac computer e.g.). This is awesome.
However, when building from Mac to Mac, it now broke the app. The error is: (also see screenshot below)

Library not loaded: @rpath/libLexActivator.dylib
Reason: image not found

<img width="432" alt="Screenshot 2020-04-15 at 22 18 40" src="https://user-images.githubusercontent.com/1948848/79385328-af253900-7f68-11ea-82df-4d6dcdba94f8.png">

I assume the binding.gyp for this repo has been changed, which is breaking the ElectronJS app, since the reference to the dynamic library is wrong.
I think the reference to the dynamic library were fine for Mac as it were in the previous version of this repo.

Thanks

/ Jens

**Comment by adnan-kamili** [comment]
Hi Jens,

There was a caching issue in the case of v3.9.1 which caused this issue. Can you confirm the library version? This should be fixed in v3.9.2

**Comment by jensstigaard** [comment]
What cache? I have tried removing the npm_modules directory and fetched all dependencies again. No luck. The error remains.

I am using lexactivator v3.9.2.

<img width="903" alt="Screenshot 2020-04-16 at 16 31 44" src="https://user-images.githubusercontent.com/1948848/79468908-d2e78e00-7fff-11ea-9e78-4ce80dd1ba1e.png">

**Comment by jensstigaard** [comment]
On a side-note: I use electron-builder - I don't know if that changes anything in regard to how it should be setup. I have used other binding libraries, which has worked with electron and electron-builder.

**Comment by adnan-kamili** [comment]
It works fine for a node.js sample app. 

Can you confirm that libLexActivator.so is copied to your app after you run electron commands. The .so file is in the same folder as lexactivator.node

**Comment by jensstigaard** [comment]
Seen below is a screenshot of the .app contents folder. libLexActivator.so is not included in the directory.
![image](https://user-images.githubusercontent.com/1948848/79470538-d4b25100-8001-11ea-9f44-f351eb993b39.png)

**Comment by jensstigaard** [comment]
Could it be the case that the .so is not listed in the libraries in the binding.gyp file, and is therefore not included in the build?

**Comment by adnan-kamili** [comment]
I am sorry I meant the dylib file which is present as shown. Where is your main.js file located?

Are you facing the same issue on Linux?

**Comment by jensstigaard** [comment]
As it is a ElectronJS app, the main.js content is inside the app.asar file.

I do not have a linux system to test with as of now.

**Comment by adnan-kamili** [comment]
Hi Jen,

We have fixed this issue by switching to static lib for compilation. We will release the new version tomorrow.

**Comment by adnan-kamili** [comment]
Fixed in v3.9.3
